### PR TITLE
Add github actions to compile objects and minor things

### PR DESCRIPTION
**Pull request by charlesneimog**
This pull request adds Github Submodules for `soundtouch` and `pd-lib-builder`, as well as Github Actions to compile the object for all platforms. 

`Note 1`: The object seems to work fine on Windows, but the help patch crashes PureData. I'm not sure what's causing the problem, but maybe we could try creating a simpler help patch for Windows. Because that I will not upload on deken, but I'd like to upload it! What do you thing?

`Note 2`: Not tested on Mac and it is just compiled for intel.

### CODE REVIEW

**Comment by porres** [comment]
e o github actions da else?

**Comment by charlesneimog** [comment]
ta funcionando tb, mas so pro Linux... Você pode baixar os binarios do ultimo commit nesse link:

https://github.com/porres/pd-else/actions, dai depois clica no ultimo commit (agora é [Merge branch 'master' of https://github.com/porres/pd-else](https://github.com/porres/pd-else/actions/runs/4714045693)) e embaixo vai ter um Zip com tudo.

Do ultimo commit:

https://github.com/porres/pd-else/actions/runs/4714045693

Com esse soundtouch é a mesma coisa... So que vai ter 3 zips, um para cada plataforma

**Comment by porres** [comment]
e o q falta pras outras plataformas?

**Comment by porres** [comment]
aproveita e ajuda lá no assunto do sfont~ ;)

**Pull request merged**
